name: is_null
description: "Check null-ness easily"
version: 1.0.0+2
repository: "https://github.com/drGlennPierce/is_null"

environment:
  sdk: ">=2.12.0 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
